
mybatis:
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com.example.demo.mapper: debug

---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testtwo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 6210
    driver-class-name: com.mysql.jdbc.Driver
    
